# Southern Tools

# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi


# Put your fun stuff here.
# Include "alias"
. ~/.user_config/no_share/alias
# General
alias genup='sudo genup -p'
#alias mv='mv -i'
#alias cp='cp -i'
#alias ln='ln -i'
#alias rm='rm -i'
alias colors='~/.user_config/scripts/colors.sh'
alias world='column /var/lib/portage/world'
alias wicd='wicd-curses'
alias calfix='. .user_config/scripts/calibre_fix.sh & calibre'
neofetch --config ~/.user_config/applications/neofetch/neofetch.conf
