#!/bin/bash
# Southern Tools
#
set -x
set -e
set -u


sbsign --key /etc/efikeys/db.key --cert /etc/efikeys/db.crt --output /var/tmp/genkernel/kernel* /var/tmp/genkernel/kernel*
mount /boot
cp /var/tmp/genkernel/kernel* /boot/EFI/Gentoo/gentoo.efi
efibootmgr -c -L "Gentoo" -l 'EFI\Gentoo\gentoo.efi'
efibootmgr -D
umount /boot
