#!/bin/bash
# Southern Tools
#
#set -x
set -e
set -u
shopt -s nullglob

# ********************** variables ********************* 
firmware_files=$"iwlwifi-7265D-* amdgpu/oland_* intel/ibt-hw-* regulatory.*"
new_kernel=$(ls -tr /boot/ | tail -n 1)
# ***************** functions ****************** 
generate_kernel() {
	echo "*** Generating Kernel with integrated initramfs ***"
	genkernel --save-config --microcode=all --mrproper --install --all-ramdisk-modules --module-rebuild --kernel-config=/proc/config.gz --lvm --luks --gpg --busybox --firmware --firmware-files="$firmware_files" --integrated-initramfs --menuconfig all
}
sign_kernel() {
	echo "*** Signing the Kernel ***"
	sbsign --key /etc/efikeys/db.key --cert /etc/efikeys/db.crt --output /boot/$new_kernel /boot/$new_kernel
}
copy_kernel_to_boot() {
	echo "*** Copying the new Kernel to the real /boot ***"
	mount /real_boot
	cp /boot/$new_kernel /real_boot/EFI/Boot/gentoo.efi
	umount /real_boot
}
boot_order () {
	echo "*** Displaying boot order ***"
	# efibootmgr -c -L "Gentoo" -l 'EFI\Boot\gentoo.efi'
	efibootmgr -D
}

# *************** start of script proper ***************
generate_kernel
sign_kernel
copy_kernel_to_boot
boot_order
# **************** end of script proper ****************
