#!/bin/bash
# Southern Tools
#
#set -x
set -e
set -u
shopt -s nullglob

# ********************** variables ********************* 
firmware_files=$"iwlwifi-7265D-* amdgpu/oland_* intel/ibt-hw-* regulatory.*"

# ***************** functions ****************** 
generate_kernel() {
	echo "*** Generating Kernel with integrated initramfs ***"
	genkernel --save-config --microcode=all --mrproper --no-install --all-ramdisk-modules --module-rebuild --kernel-config=/proc/config.gz --no-mountboot --lvm --luks --gpg --busybox --firmware --firmware-files="$firmware_files" --integrated-initramfs --menuconfig all
}
sign_kernel() {
	echo "*** Signing the Kernel ***"
	sbsign --key /etc/efikeys/db.key --cert /etc/efikeys/db.crt --output /var/tmp/genkernel/kernel* /var/tmp/genkernel/kernel*
}
copy_kernel_to_boot() {
	echo "*** Copying the new Kernel to the real /boot ***"
	mount /boot
	cp /var/tmp/genkernel/kernel* /boot/EFI/Boot/gentoo.efi
	umount /boot
}
boot_order () {
	echo "*** Displaying boot order ***"
	# efibootmgr -c -L "Gentoo" -l 'EFI\Boot\gentoo.efi'
	efibootmgr -D
}
kernel_backup () {
	echo "*** Backing up the kernel ***"
	cp /var/tmp/genkernel/* /boot
}
# *************** start of script proper ***************
generate_kernel
sign_kernel
copy_kernel_to_boot
boot_order
kernel_backup
# **************** end of script proper ****************
