# Southern Tools

# /etc/skel/.bash_profile
#
# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
if [[ -f ~/.bashrc ]] ; then
	. ~/.bashrc
fi


# Export variables
export PATH="$(du $HOME/.user_config/scripts/ | cut -f2 | tr '\n' ':')$PATH"
export RXVT_SOCKET="/tmp/urxvt-socket"
export VDPAU_DRIVER="i965"
#export QT_AUTO_SCREEN_SCALE_FACTOR="1"
export GDK_SCALE="2"
export GDK_DPI_SCALE="0.5"
export CALIBRE_USE_SYSTEM_THEME=1

# Wayland variables
#export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel ${_JAVA_OPTIONS}"
#export WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1
#export XKB_DEFAULT_LAYOUT=es

# Set XDG_RUNTIME_DIR for Sway to work
if test -z "${XDG_RUNTIME_DIR}"; then
    export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
    fi
fi


## Autologin to Sway
#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec sway -c ~/.user_config/applications/sway/config; fi


## Autologin to Sway with log
#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec sway -c ~/.user_config/applications/sway/config -d 2> ~/sway.log; fi


## Auto-login to i3wm
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec startx; fi
