# Southern Tools

# /etc/skel/.bash_profile
#
# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
#if [[ -f ~/.bashrc ]] ; then
#	. ~/.bashrc
#fi

# Set XDG_RUNTIME_DIR for Sway to work without elogind
#if test -z "${XDG_RUNTIME_DIR}"; then
#    export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
#    if ! test -d "${XDG_RUNTIME_DIR}"; then
#        mkdir "${XDG_RUNTIME_DIR}"
#        chmod 0700 "${XDG_RUNTIME_DIR}"
#    fi
#fi

# System Variables
#export RXVT_SOCKET="/tmp/urxvt-socket"
export PATH="$(du $HOME/.user_config/scripts/ | cut -f2 | tr '\n' ':')$PATH"
export VDPAU_DRIVER="i965"
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel ${_JAVA_OPTIONS}"
#export DRI_PRIME=1
#export VK_ICD_FILENAMES=/opt/amdgpu-pro/etc/vulkan/icd.d/amd_icd64.json

# GTK+ variables
#export GDK_BACKEND="wayland"
#export GDK_SCALE="2"
#export GDK_DPI_SCALE="0.5"

# QT5 Variables
#export CALIBRE_USE_SYSTEM_THEME="1"
#export QT_AUTO_SCREEN_SCALE_FACTOR="1"
#export QT_SCALE_FACTOR="1.25"
#export WINIT_HIDPI_FACTOR="1"

# Wayland variables
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_FORCE_DPI=physical
export MOZ_ENABLE_WAYLAND=1
export BEMENU_BACKEND=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export SDL_VIDEODRIVER=wayland
#export WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/renderD128 sway

# Autologin to Sway
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then dbus-launch --exit-with-session sway -c ~/.user_config/applications/sway/config; fi

# Autologin to Sway with log
#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then dbus-launch --exit-with-session sway -c ~/.user_config/applications/sway/config -d 2> ~/sway.log; fi

# Auto-login to i3wm
#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec startx; fi
