#!/bin/zsh
# Southern Tools
#
# Completion
autoload -U compinit
compinit

# Default completion style is quite plain and ugly.
#zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*' menu select
#zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'
zstyle ':completion:*:warnings' format '%BSorry, no matches'

# Correction
setopt correctall

# Load Pure
fpath+=$HOME/Remotes/git_only_pull/sindresorhus/pure/
# Prompt
autoload -U promptinit
promptinit
prompt pure

# History
export HISTSIZE=10000
export HISTFILE="/tmp/zsh_history"
export SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups
setopt hist_ignore_space

# Modules
source /usr/share/zsh/site-functions/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(brackets cursor line main pattern regexp root)

# Misc
setopt autocd
setopt extendedglob

# Put your fun stuff here.
# Include "alias"
. ~/.user_config/no_share/alias
# General
alias genup='sudo genup'
alias cp='cp -i'
alias ln='ln -i'
alias mv='mv -i'
alias rm='rm -i'
alias ls='ls --color=auto'
alias world='column /var/lib/portage/world'
alias repos='~/.user_config/scripts/update_git_repos.sh'
alias mupdate='repos && genup'
alias colors='. ~/.user_config/scripts/colors.sh'
alias myip='curl https://api.ipify.org/'
#alias calfix='. .user_config/scripts/calibre_fix.sh & calibre'
#alias steam='DRI_PRIME=1 steam'
neofetch --config ~/.user_config/applications/neofetch/neofetch.conf
