#!/bin/zsh
# Southern Tools
#
# Completion
autoload -U compinit
compinit

# Default completion style is quite plain and ugly.
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'

# Correction
setopt correctall

# Load Pure
fpath+=$HOME/Remotes/git_only_pull/pure_zsh

# Prompt
autoload -U promptinit
promptinit
prompt pure

# History
export HISTSIZE=10000
export HISTFILE="/tmp/zsh_history"
export SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups
setopt hist_ignore_space

# Modules
source /usr/share/zsh/site-functions/zsh-syntax-highlighting.zsh

# Misc
setopt autocd
setopt extendedglob

# Put your fun stuff here.
# Include "alias"
. ~/.user_config/no_share/alias
# General
alias genup='sudo genup'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias rm='rm -i'
alias world='column /var/lib/portage/world'
neofetch --config ~/.user_config/applications/neofetch/neofetch.conf

