#!/bin/zsh
# Southern Tools
#
# Completion
autoload -U compinit
compinit

#Default completion style is quite plain and ugly.
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'

# Correction
setopt correctall

# Prompt
autoload -U promptinit
promptinit
prompt gentoo

# History
export HISTSIZE=10000
export HISTFILE="/tmp/.zsh_history"
export SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt autocd

# Put your fun stuff here.
# Include "alias"
. ~/.user_config/no_share/alias
# General
alias genup='sudo genup'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias rm='rm -i'
alias colors='~/.user_config/scripts/colors.sh'
alias world='column /var/lib/portage/world'
alias wicd='wicd-curses'
neofetch --config ~/.user_config/applications/neofetch/neofetch.conf

