# Southern Tools
#
export NUMCPUS=$(nproc)
export NUMCPUSPLUSONE=$(( NUMCPUS + 1 ))
export MAKEOPTS="-j${NUMCPUSPLUSONE} -l${NUMCPUS}"
export EMERGE_DEFAULT_OPTS="--jobs=${NUMCPUSPLUSONE} --load-average=${NUMCPUS} --keep-going=y"

# Aliases
alias up='emerge -av --deep --with-bdeps=y --changed-use --update --backtrack=50 @world'
alias make.conf='nano /etc/portage/make.conf'
alias use='nano /etc/portage/package.use'
alias mask='nano /etc/portage/package.mask'
alias unmask='nano /etc/portage/package.unmask'
alias keywords='nano /etc/portage/package.accept_keywords'
alias license='nano /etc/portage/package.license'
alias cflags='nano /etc/portage/package.cflags/southern_ltoworkarounds.conf'